variables:
  # Simple variables
  userName: TestUser
  groupName: TestGroup

  # Variable with a value that is a hashtable
  foo:
    bar: baz

resources:
  - name: test-user
    type: PSDscResources/User
    properties:
      UserName: $userName # This is an example of how to use a simple variable
    register: testuser_output # Register the results of the Get method to a variable named 'testuser_output'. Get is called after Set.
    
  - condition: $foo.bar -ne "baz" # when is a condition that must return $true or else this task will be skipped
    name: test-group
    type: PSDscResources/Group
    properties:
      GroupName: $($testuser_output.UserName) # This is an example of using a hashtable variable.
    register: testgroup_output

  - name: spooler-service
    type: PSDscResources/Service
    properties:
      Name: Spooler

  - name: timezone
    type: xTimeZone/xTimeZone
    properties:
      TimeZone: Pacific Standard Time
      IsSingleInstance: yes
