parameters:
  timeZone:
    type: string
    defaultValue: Pacific Standard Time

variables:
  # Simple variables
  userName: TestUser
  groupName: TestGroup

  foo: # Variable with a value that is a hashtable
    bar: baz

resources:
  - name: test-user # The results of the Get method are stored in a variable named 'test-user'. Get is called after Set. When name contains a special character, use ${test user}
    type: PSDscResources/User
    properties:
      UserName: $(variables('userName')) # This is an example of how to use a simple variable
    
  - name: test-group
    type: PSDscResources/Group
    properties:
      GroupName: $(variables('groupName'))
      MembersToInclude:
        - $($(reference('test-user')).UserName)

  - condition: $(not(equals($(variables('foo')).bar, 'baz'))) # Conditions must return $true or else this task will be skipped
    name: spooler-service
    type: PSDscResources/Service
    properties:
      Name: Spooler

  - name: timezone
    type: xTimeZone/xTimeZone
    properties:
      TimeZone: $(parameters('timeZone'))
      IsSingleInstance: yes
